# Generated by Django 3.2.6 on 2021-09-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceItem',
            fields=[
                ('item_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('min_enhance', models.IntegerField()),
                ('max_enhance', models.IntegerField()),
                ('base_price', models.BigIntegerField(blank=True, null=True)),
                ('in_stock', models.BigIntegerField(blank=True, null=True)),
                ('total_trades', models.BigIntegerField(blank=True, null=True)),
                ('min_price_list', models.BigIntegerField(blank=True, null=True)),
                ('max_price_list', models.BigIntegerField(blank=True, null=True)),
                ('last_sale_price', models.BigIntegerField(blank=True, null=True)),
                ('last_sale_time', models.CharField(blank=True, max_length=32, null=True)),
                ('item_type', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'marketplace_items',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='MarketplaceItems',
        ),
    ]
