# Generated by Django 3.2.6 on 2021-09-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceapp', '0004_alter_cookingitem_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlchemyItem',
            fields=[
                ('item_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('min_enhance', models.IntegerField()),
                ('max_enhance', models.IntegerField()),
                ('base_price', models.BigIntegerField(blank=True, null=True)),
                ('in_stock', models.BigIntegerField(blank=True, null=True)),
                ('total_trades', models.BigIntegerField(blank=True, null=True)),
                ('min_price_list', models.BigIntegerField(blank=True, null=True)),
                ('max_price_list', models.BigIntegerField(blank=True, null=True)),
                ('last_sale_price', models.BigIntegerField(blank=True, null=True)),
                ('last_sale_time', models.CharField(blank=True, max_length=32, null=True)),
                ('item_type', models.CharField(max_length=32)),
                ('grade', models.IntegerField()),
                ('profession_level', models.CharField(max_length=32)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'alchemy_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FarmingItem',
            fields=[
                ('item_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('min_enhance', models.IntegerField()),
                ('max_enhance', models.IntegerField()),
                ('base_price', models.BigIntegerField(blank=True, null=True)),
                ('in_stock', models.BigIntegerField(blank=True, null=True)),
                ('total_trades', models.BigIntegerField(blank=True, null=True)),
                ('min_price_list', models.BigIntegerField(blank=True, null=True)),
                ('max_price_list', models.BigIntegerField(blank=True, null=True)),
                ('last_sale_price', models.BigIntegerField(blank=True, null=True)),
                ('last_sale_time', models.CharField(blank=True, max_length=32, null=True)),
                ('item_type', models.CharField(max_length=32)),
                ('grade', models.IntegerField()),
                ('fruit', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'farming_items',
                'managed': False,
            },
        ),
    ]
