# Generated by Django 3.2.6 on 2021-09-14 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceapp', '0003_cookingitem'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cookingitem',
            table='cooking_items',
        ),
    ]
