# Generated by Django 3.2.6 on 2021-09-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceapp', '0006_fruititem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PearlItem',
            fields=[
                ('item_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('base_price', models.BigIntegerField(blank=True, null=True)),
                ('in_stock', models.BigIntegerField(blank=True, null=True)),
                ('total_trades', models.BigIntegerField(blank=True, null=True)),
                ('hourly_sale', models.IntegerField()),
                ('daily_sale', models.IntegerField()),
                ('weekly_sale', models.IntegerField()),
                ('monthly_sale', models.IntegerField()),
                ('grade', models.IntegerField()),
            ],
            options={
                'db_table': 'pearl_items',
                'managed': False,
            },
        ),
    ]
